### PR TITLE
Nav foot responsive

### PR DESCRIPTION
**Pull request by blacktomang**
**Ngayal bisa cepet :V**

### CODE REVIEW

**Review by suarminrais — CHANGES_REQUESTED** [review]
always KISS principle.
To much unnecessary code and also code duplication.

For responsive thing use media query.

**Comment by suarminrais** [comment]
Masih ada li cok

**Comment by suarminrais** [comment]
Linya di navbar style aja yg berubah. Di component sama aja

**Comment by blacktomang** [comment]
gimana cuk, gapaham.

di component tetep ada tag li?

**Comment by suarminrais** [comment]
Nice

**Pull request merged**
